# Requires a .env file in the same directory as this file

services:
  discovarr:
    container_name: discovarr
    environment:
      LOGLEVEL: ${LOGLEVEL}
      TZ: ${TZ}
      VITE_DISCOVARR_URL: ${VITE_DISCOVARR_URL}
      JELLYFIN_URL: ${JELLYFIN_URL}
      JELLYFIN_API_KEY: ${JELLYFIN_API_KEY}
      PLEX_API_TOKEN: ${PLEX_API_TOKEN}
      PLEX_URL: ${PLEX_URL}
      APP_RECENT_LIMIT: ${APP_RECENT_LIMIT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
      GEMINI_LIMIT: ${GEMINI_LIMIT}
      RADARR_URL: ${RADARR_URL}
      RADARR_API_KEY: ${RADARR_API_KEY}
      SONARR_URL: ${SONARR_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
    image: ghcr.io/sqrlmstr5000/discovarr:latest
    network_mode: bridge
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./cache:/cache